const cocktails = [
  {
    id: 0,
    name: "ARCANE IN WONDERLAND",
    ingredients: [
      "5cl Arcane Extraroma",
      "2cl Vermouth Dry",
      "4cl Cream",
      "4cl Egg White",
      "Grated Tonka Bean",
      "3 dashes Bitters J.M Cacao Forastero",
    ],
    image: "/assets/cocktails/cocktailTest.webp",
  },
  {
    id: 1,
    name: "Arcane in Wonderland",
    ingredients: [
      "5cl Arcane Extraroma",
      "2cl Vermouth Dry",
      "4cl Cream",
      "4cl Egg White",
      "Grated Tonka Bean",
      "3 dashes Bitters J.M Cacao Forastero",
    ],
    description: "A magical journey into flavors and textures.",
    image: "/assets/cocktails/cocktailTest.webp",
  },
  {
    id: 2,
    name: "Arcane in Wonderland",
    ingredients: [
      "5cl Arcane Extraroma",
      "2cl Vermouth Dry",
      "4cl Cream",
      "4cl Egg White",
      "Grated Tonka Bean",
      "3 dashes Bitters J.M Cacao Forastero",
    ],
    description: "A magical journey into flavors and textures.",
    image: "/assets/cocktails/cocktailTest.webp",
  },
  {
    id: 3,
    name: "Arcane in Wonderland",
    ingredients: [
      "5cl Arcane Extraroma",
      "2cl Vermouth Dry",
      "4cl Cream",
      "4cl Egg White",
      "Grated Tonka Bean",
      "3 dashes Bitters J.M Cacao Forastero",
    ],
    description: "A magical journey into flavors and textures.",
    image: "/assets/cocktails/cocktailTest.webp",
  },
  {
    id: 4,
    name: "Arcane in Wonderland",
    ingredients: [
      "5cl Arcane Extraroma",
      "2cl Vermouth Dry",
      "4cl Cream",
      "4cl Egg White",
      "Grated Tonka Bean",
      "3 dashes Bitters J.M Cacao Forastero",
    ],
    description: "A magical journey into flavors and textures.",
    category: "Créations",
    image: "/assets/cocktails/cocktailTest.webp",
  },
  {
    id: 5,
    name: "Arcane in Wonderland",
    ingredients: [
      "5cl Arcane Extraroma",
      "2cl Vermouth Dry",
      "4cl Cream",
      "4cl Egg White",
      "Grated Tonka Bean",
      "3 dashes Bitters J.M Cacao Forastero",
    ],
    description: "A magical journey into flavors and textures.",
    image: "/assets/cocktails/cocktailTest.webp",
    category: "Créations",
  },
];

export default cocktails;